import '../styles/App.css'
import SkillItem from './atoms/SkillItem'

const Skills = () => {
    return <section id='skills' className='w-full py-16 md:py-24'>
        <div className='w-full max-w-7xl mx-auto'>
            
            <div className='flex flex-col items-center gap-4 mb-12'>
                <div className='inline-flex items-center gap-2'>
                    <span className='text-green-600 tracking-[0.5em] font-bold font-Quick text-sm md:text-base uppercase'>
                        Stack Tecnológico
                    </span>
                </div>
                <h2 className='text-text-primary font-Quick font-black text-3xl md:text-4xl text-center'>
                    Tecnologías que domino
                </h2>
            </div>

            <div className='overflow-hidden space-y-8 z-50
            [mask-image:linear-gradient(to_right,transparent,black_20%,black_90%,transparent)]
            [-webkit-mask-image:linear-gradient(to_right,transparent,black_20%,black_90%,transparent)]
            '>
                <div className='
                    inline-flex 
                    animate-skills-left-spin 
                    whitespace-nowrap 
                    will-change-transform 
                    gap-0
                    hover:[animation-play-state:paused]'>
                    <div className='flex justify-center gap-4'>
                        <SkillItem 
                            url={"https://astro.build/"}
                            skill={"astro"}
                        />
                        <SkillItem 
                            url={"https://nextjs.org/"}
                            skill={"nextjs"}
                        />
                        <SkillItem 
                            url={"https://react.dev/"}
                            skill={"react"}
                        />
                        <SkillItem 
                            url={"https://tailwindcss.com/"}
                            skill={"tailwind"}
                        />
                        <SkillItem 
                            url={"https://developer.mozilla.org/es/docs/Web/HTML"}
                            skill={"html"}
                        />
                        <SkillItem 
                            url={"https://developer.mozilla.org/es/docs/Web/CSS"}
                            skill={"css"}
                        />
                        <SkillItem 
                            url={"https://developer.mozilla.org/es/docs/Web/JavaScript"}
                            skill={"javascript"}
                        />
                        <SkillItem 
                            url={"https://www.python.org/"}
                            skill={"python"}
                        />
                        <SkillItem 
                            url={"https://www.djangoproject.com/"}
                            skill={"django"}
                        />
                    </div>
                    <div aria-hidden className='flex justify-center gap-4'>
                        <SkillItem 
                            url={"https://astro.build/"}
                            skill={"astro"}
                        />
                        <SkillItem 
                            url={"https://nextjs.org/"}
                            skill={"nextjs"}
                        />
                        <SkillItem 
                            url={"https://react.dev/"}
                            skill={"react"}
                        />
                        <SkillItem 
                            url={"https://tailwindcss.com/"}
                            skill={"tailwind"}
                        />
                        <SkillItem 
                            url={"https://developer.mozilla.org/es/docs/Web/HTML"}
                            skill={"html"}
                        />
                        <SkillItem 
                            url={"https://developer.mozilla.org/es/docs/Web/CSS"}
                            skill={"css"}
                        />
                        <SkillItem 
                            url={"https://developer.mozilla.org/es/docs/Web/JavaScript"}
                            skill={"javascript"}
                        />
                        <SkillItem 
                            url={"https://www.python.org/"}
                            skill={"python"}
                        />
                        <SkillItem 
                            url={"https://www.djangoproject.com/"}
                            skill={"django"}
                        />
                    </div>
                    <div aria-hidden className='flex justify-center gap-4'>
                        <SkillItem 
                            url={"https://astro.build/"}
                            skill={"astro"}
                        />
                        <SkillItem 
                            url={"https://nextjs.org/"}
                            skill={"nextjs"}
                        />
                        <SkillItem 
                            url={"https://react.dev/"}
                            skill={"react"}
                        />
                        <SkillItem 
                            url={"https://tailwindcss.com/"}
                            skill={"tailwind"}
                        />
                        <SkillItem 
                            url={"https://developer.mozilla.org/es/docs/Web/HTML"}
                            skill={"html"}
                        />
                        <SkillItem 
                            url={"https://developer.mozilla.org/es/docs/Web/CSS"}
                            skill={"css"}
                        />
                        <SkillItem 
                            url={"https://developer.mozilla.org/es/docs/Web/JavaScript"}
                            skill={"javascript"}
                        />
                        <SkillItem 
                            url={"https://www.python.org/"}
                            skill={"python"}
                        />
                        <SkillItem 
                            url={"https://www.djangoproject.com/"}
                            skill={"django"}
                        />
                    </div>
                </div>

                <div className='
                    inline-flex 
                    animate-skills-right-spin 
                    whitespace-nowrap 
                    will-change-transform 
                    gap-0
                    hover:[animation-play-state:paused]'>
                    <div aria-hidden className='flex justify-center gap-4'>
                        <SkillItem 
                            url={"https://reflex.dev/"}
                            skill={"reflex"}
                            ico={"/reflex.ico"}
                        />
                        <SkillItem 
                            url={"https://getbootstrap.com/"}
                            skill={"bootstrap"}
                        />
                        <SkillItem 
                            url={"https://git-scm.com/"}
                            skill={"git"}
                        />
                        <SkillItem 
                            url={"https://www.microsoft.com/es-es/sql-server"}
                            skill={"mssql"}
                        />
                        <SkillItem 
                            url={"https://www.mongodb.com/"}
                            skill={"mongodb"}
                        />
                        <SkillItem 
                            url={"https://nodejs.org/es"}
                            skill={"nodejs"}
                        />
                        <SkillItem 
                            url={"https://zustand-demo.pmnd.rs/"}
                            skill={"zustand"}
                            ico={"/zustand.ico"}
                        />
                        <SkillItem 
                            url={"https://expressjs.com/"}
                            skill={"expressjs"}
                        />
                        <SkillItem 
                            url={"https://strapi.io/"}
                            skill={"strapi"}
                        />
                    </div>

                    <div className='flex justify-center gap-4'>            
                        <SkillItem 
                            url={"https://reflex.dev/"}
                            skill={"reflex"}
                            ico={"/reflex.ico"}
                        />
                        <SkillItem 
                            url={"https://getbootstrap.com/"}
                            skill={"bootstrap"}
                        />
                        <SkillItem 
                            url={"https://git-scm.com/"}
                            skill={"git"}
                        />
                        <SkillItem 
                            url={"https://www.microsoft.com/es-es/sql-server"}
                            skill={"mssql"}
                        />
                        <SkillItem 
                            url={"https://www.mongodb.com/"}
                            skill={"mongodb"}
                        />
                        <SkillItem 
                            url={"https://nodejs.org/es"}
                            skill={"nodejs"}
                        />
                        <SkillItem 
                            url={"https://zustand-demo.pmnd.rs/"}
                            skill={"zustand"}
                            ico={"/zustand.ico"}
                        />
                        <SkillItem 
                            url={"https://expressjs.com/"}
                            skill={"expressjs"}
                        />
                        <SkillItem 
                            url={"https://strapi.io/"}
                            skill={"strapi"}
                        />
                    </div>
                    <div aria-hidden className='flex justify-center gap-4'>
                        <SkillItem 
                            url={"https://reflex.dev/"}
                            skill={"reflex"}
                            ico={"/reflex.ico"}
                        />
                        <SkillItem 
                            url={"https://getbootstrap.com/"}
                            skill={"bootstrap"}
                        />
                        <SkillItem 
                            url={"https://git-scm.com/"}
                            skill={"git"}
                        />
                        <SkillItem 
                            url={"https://www.microsoft.com/es-es/sql-server"}
                            skill={"mssql"}
                        />
                        <SkillItem 
                            url={"https://www.mongodb.com/"}
                            skill={"mongodb"}
                        />
                        <SkillItem 
                            url={"https://nodejs.org/es"}
                            skill={"nodejs"}
                        />
                        <SkillItem 
                            url={"https://zustand-demo.pmnd.rs/"}
                            skill={"zustand"}
                            ico={"/zustand.ico"}
                        />
                        <SkillItem 
                            url={"https://expressjs.com/"}
                            skill={"expressjs"}
                        />
                        <SkillItem 
                            url={"https://strapi.io/"}
                            skill={"strapi"}
                        />
                    </div>
                </div>
            </div>
        </div>
    </section>
}

export default Skills